#cloud-config

package_update: true

packages:
  - nginx

write_files:
  - path: /var/www/html/index.html
    permissions: "0644"
    content: |
      <!DOCTYPE html>
      <html>
      <head>
        <title>Terraform Cloud-Init Lab</title>
      </head>
      <body style="font-family: Arial; text-align: center; margin-top: 80px;">
        <h1>Terraform + Cloud-Init</h1>
        <p>This NGINX server was automatically configured using cloud-init.</p>
        <p>No manual configuration was required.</p>
      </body>
      </html>

runcmd:
  - systemctl enable nginx
  - systemctl restart nginx

