# Docker Compose file for the Flask application and MySQL database

version: '3.8'

services:
  web:
    image: my-flask-app:multistage
    ports:
      - "5000:5000"
    depends_on:
      - mydb

  mydb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
