name: Custom Action

description: Greet someone

inputs:
  who-to-greet:
    description: who to greet
    required: true
    default: Hello

outputs:
  time:
    description: the time you were greeted

runs:
  using: node24
  main: dist/index.js
